# 보스턴 주택가격 예측

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
boston = pd.read_csv('boston.csv')
독립 = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = boston[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [4]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [10]:
model.summary()
# param = 학습하는 가중치 개수

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_1 (Dense)             (None, 10)                140       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151 (604.00 Byte)
Trainable params: 151 (604.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 589us/step - loss: 19.1671
Epoch 2/10
16/16 [==============================] - 0s 617us/step - loss: 18.8409
Epoch 3/10
16/16 [==============================] - 0s 724us/step - loss: 18.7678
Epoch 4/10
16/16 [==============================] - 0s 776us/step - loss: 17.7520
Epoch 5/10
16/16 [==============================] - 0s 693us/step - loss: 19.1940
Epoch 6/10
16/16 [==============================] - 0s 777us/step - loss: 19.9531
Epoch 7/10
16/16 [==============================] - 0s 623us/step - loss: 19.1631
Epoch 8/10
16/16 [==============================] - 0s 733us/step - loss: 17.5796
Epoch 9/10
16/16 [==============================] - 0s 736us/step - loss: 18.6968
Epoch 10/10
16/16 [==============================] - 0s 684us/step - loss: 19.6622


In [11]:
print(model.predict(독립[:5]))
print(종속[:5])
      
      

1/1 [==============================] - 0s 58ms/step
[[28.545595]
 [21.586884]
 [29.196957]
 [33.423283]
 [32.097595]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [19]:
iris = pd.read_csv('iris.csv')
iris = pd.get_dummies(iris) # dummies = 원핫 인코딩

In [20]:
a = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
b = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [26]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)  # 비율로 예측하기 위해 활성화함수 = softmax 사용
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics = 'accuracy')

In [28]:
model.fit(a, b, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0835 - accuracy: 0.9733
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0810 - accuracy: 0.9867
Epoch 3/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0805 - accuracy: 0.9800
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0808 - accuracy: 0.9867
Epoch 5/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0839 - accuracy: 0.9667
Epoch 6/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0799 - accuracy: 0.9800
Epoch 7/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0780 - accuracy: 0.9733
Epoch 8/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0791 - accuracy: 0.9800
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0741 - accuracy: 0.9800
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.0804 - accuracy: 0.9800
Epoch 11/100
5/5 [===========

5/5 [==============================] - 0s 1ms/step - loss: 0.0595 - accuracy: 0.9867
Epoch 85/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0626 - accuracy: 0.9733
Epoch 86/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0616 - accuracy: 0.9867
Epoch 87/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0587 - accuracy: 0.9733
Epoch 88/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0643 - accuracy: 0.9800
Epoch 89/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0598 - accuracy: 0.9867
Epoch 90/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0577 - accuracy: 0.9867
Epoch 91/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0649 - accuracy: 0.9867
Epoch 92/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0611 - accuracy: 0.9800
Epoch 93/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0585 - accuracy: 0.9867
Epoch 94/100
5/5 [===============

In [32]:
print(model.predict(a[0:5]))
print(b[0:5])

1/1 [==============================] - 0s 12ms/step
[[9.9999630e-01 3.7342918e-06 2.4801732e-09]
 [9.9997926e-01 2.0793281e-05 1.5087675e-08]
 [9.9999011e-01 9.9502950e-06 1.0723088e-08]
 [9.9994123e-01 5.8726800e-05 3.2315576e-08]
 [9.9999642e-01 3.6039178e-06 2.4239590e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
